---
branch: master
repositoryUrl: https://github.com/AndreyMork/mergy.git
tagFormat: v${version}
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/git'
  - '@semantic-release/github'
dryRun: false
ci: false
